fix CRM模块-（线索+客户）增加字段 (#53)
* fix crm添加了5个字段、增加验证字典还没有判断。

* fix  CrmCustomer 增加5个查询入参

* fix  1、删除多选查询
原始代码有问题。例如更新线索的时候aop的spEL异常。
org.springframework.expression.spel.SpelEvaluationException: EL1007E: Property or field 'id' cannot be found on null

* fix 完善了bo的字段。
2、修复线索转换客户时字段丢失。


* fix 删除公司变量、完善跟进类型+客户来源分类字典。
2、修复SpelEvaluationException异常。

* fix 修改公司介绍命名


* fix 增加导入服务实现类

* Revert "fix 增加导入服务实现类"

This reverts commit 125ec380299222caf6ad75bf3aea1487e1ab576f.

* Revert "fix 修改"

This reverts commit 8d05b397b20b2c35578acdd19b22c6b3c6b2d02a.

* Update DictTypeConstants.java

* fix 修改crm枚举名称

---------

Co-authored-by: c-tao <schwarzft@gmail.com>